main: fr.oramni.palaenderchest.PalaEnderChest
name: PalaEnderChest
version: 1.0
author: Oramni
commands:
  enderchest:
    description: Pour ouvrir enderchest
  ec:
    description: Pour ouvrir enderchest